GET http://localhost:8080/

### local

POST http://localhost:7071/api/quote
content-type: application/json

{
   "age": 8,
   "breed": "chow"
}

### local

POST https://dogop-serverless-746651650023.europe-west10.run.app/api/quote
content-type: application/json

{
   "age": 8,
   "breed": "chow"
}

### Azure Function App

POST https://dogop-serverless-quote.azurewebsites.net/api/quote
content-type: application/json

{
   "age": 8,
   "breed": "chow"
}

###

POST https://europe-west10-dogop-serverless.cloudfunctions.net/quote
content-type: application/json

{
   "age": 8,
   "breed": "chow"
}

### Container App

POST https://dogop-serverless.livelyground-3e6e8048.westeurope.azurecontainerapps.io/api/quote
content-type: application/json

{
   "age": 8,
   "breed": "chow"
}


###

POST http://localhost:8080/api/offer
content-type: application/json

{
   "name": "Rollo",
   "age": 8,
   "breed": "chow",
   "customer": "jan"
}


###

GET http://localhost:8080/api/offer/427ed4de-6f51-4a09-baad-e3c2f962d2fe
